In [1]:
import numpy as np
import os
import pandas as pd
from pathlib import *

In [2]:
csvlist = []

In [3]:
pwd = os.getcwd()
pwd

'E:\\kaggle\\newsclassification\\正式比赛用的代码'

In [4]:
#获取当前文件夹下所有文件名
for root, dirs, files in os.walk(r"E:\kaggle\newsclassification\正式比赛用的代码\1", topdown=False):
    for name in files:
        path = PurePath(name)
        csvlist.append(path.name)

In [5]:
csvlist

['1hwwTaowa_Final1.csv',
 '95.02bert_dev96.63.csv',
 '95.28bert_dev96.60.csv',
 '95.39bert_dev96.66.csv',
 '95.79bert_dev96.67.csv',
 'bert._dev95.59.csv',
 'bert60wnew_10(1)_96.35.csv',
 'bert60wnew_12_96.29.csv',
 'bert60w_10_hww96.37.csv',
 'bert60w_13_hww96.3.csv',
 'bert_oldbert96.63.csv',
 'hww未知1bert60wpp_10(1).csv',
 'hww未知2bert60w_17(1).csv']

In [6]:
test_pred = np.zeros((50000, 1), int) 
test_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [8]:
for csv in csvlist:
    dirpath = Path("./1")
    filepath = dirpath.joinpath(csv)
    print(filepath)
    df = pd.read_csv(filepath)
    test_pred = np.column_stack((test_pred, df.values))

1\1hwwTaowa_Final1.csv
1\95.02bert_dev96.63.csv
1\95.28bert_dev96.60.csv
1\95.39bert_dev96.66.csv
1\95.79bert_dev96.67.csv
1\bert._dev95.59.csv
1\bert60wnew_10(1)_96.35.csv
1\bert60wnew_12_96.29.csv
1\bert60w_10_hww96.37.csv
1\bert60w_13_hww96.3.csv
1\bert_oldbert96.63.csv
1\hww未知1bert60wpp_10(1).csv
1\hww未知2bert60w_17(1).csv


In [9]:
test_pred.shape

(50000, 14)

In [10]:
test_pred

array([[ 0,  6,  6, ...,  6,  6,  6],
       [ 0, 13, 13, ..., 13, 13, 13],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  1,  1, ...,  1,  1,  1],
       [ 0,  4,  4, ...,  4,  4,  4],
       [ 0, 12, 12, ..., 12, 12, 12]], dtype=int64)

In [11]:
test_pred[40]

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [12]:
eff_test = test_pred[:,1:]

In [13]:
eff_test

array([[ 6,  6,  6, ...,  6,  6,  6],
       [13, 13, 13, ..., 13, 13, 13],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 4,  4,  4, ...,  4,  4,  4],
       [12, 12, 12, ..., 12, 12, 12]], dtype=int64)

In [14]:
eff_test.shape

(50000, 13)

In [15]:
preds = []
for i, test_list in enumerate(test_pred):
    preds.append(np.argmax(np.bincount(test_list)))
    print(np.bincount(test_list))
preds = np.array(preds)

[ 1  0  0  0  0  0 13]
[ 1  0  0  0  0  0  0  0  0  0  0  0  0 13]
[14]
[ 1  0  0 13]
[14]
[ 1  0  0 13]
[ 1 13]
[11  0  0  0  0  3]
[ 1 13]
[ 1  0  0  0  0  0  0 13]
[1 0 0 0 0 0 4 0 0 0 0 9]
[ 1  0  0  0  0  0  0  0  0  0  0 13]
[ 1  0  0 13]
[14]
[ 1  0  0  0  0  0  0  0 13]
[14]
[ 1  0  0  0  0  0 13]
[ 1  0  0  0  0  0 13]
[ 1 13]
[ 1  0  0  0  0  0  0  0  0 13]
[ 1 13]
[ 1  0  0  0 13]
[ 1  0 13]
[14]
[ 1  0 13]
[ 1  0 13]
[14]
[6 0 0 8]
[ 1  0  0  0  0  0  0  0  0 13]
[ 1  0  0  0  0  0 13]
[ 1  0  0 13]
[ 1  0 13]
[ 1  0  0 13]
[ 1  0 13]
[ 1  0 13]
[ 1  0  0  0  0  0  0  0 13]
[14]
[14]
[13  0  0  0  0  0  1]
[ 1 13]
[ 1 13]
[14]
[ 1  0  0  0  0  0  0  0  0  0 13]
[14]
[ 1  0  0  0  0 13]
[ 1  0 13]
[ 1 13]
[14]
[14]
[ 1  0  0 13]
[ 1  0  0  0  0  0 13]
[ 1  0  0  0  0 13]
[14]
[ 1  0  0  0  0  0  0  0  0 13]
[ 1  0  0 13]
[ 1  0 12  0  0  0  0  0  0  0  0  0  1]
[14]
[ 1 13]
[ 1  0 13]
[14]
[ 1  0  0  0  0  0  0  0  0  0 13]
[ 1  0  0  0  0  0  0 13]
[ 1 13]
[14]
[ 1  0  0  0

limit_output extension: Maximum message size of 10000 exceeded with 10370 characters

In [16]:
preds

array([ 6, 13,  0, ...,  1,  4, 12], dtype=int64)

In [17]:
preds[40]

1

In [18]:
preds[0]

6

In [19]:
submission = pd.read_csv('E:/kaggle/newsclassification/input/test_a_sample_submit.csv')
submission['label'] = preds
submission.to_csv('E:/kaggle/newsclassification/output/my_taowa_1.csv', index=False)

In [111]:
x = np.array([0, 1, 1, 3, 2, 1, 7])

In [112]:
np.bincount(x)

array([1, 3, 1, 1, 0, 0, 0, 1], dtype=int64)

In [ ]:
#上面意思0出现1次3出现两次，2出现一次，3出现一次